[workspace]
authors = ["kozo <kozoYang@outlook.com>"]
channels = [
  "https://prefix.dev/meta-forge",
  "conda-forge",
]
name = "profiling"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.7"
[dependencies]
cuda = "12.6.*"
pytorch = { version = "==2.5.1", build = "*cuda*" }
python = "3.10.*"
pip = "*"
opencv = "*"
torchaudio = { version = "==2.5.1", build = "*cuda*" }
ffmpeg = "*"
huggingface_hub = ">=0.30.2,<0.31"
transformers = ">=4.51.1,<5"
accelerate = ">=1.5.2,<2"
tensorboard = ">=2.19.0,<3"
tree = ">=2.2.1,<3"
nsight-compute = ">=2024.3.2.3,<2025"
